
--- トリガー

CREATE OR REPLACE TRIGGER TEXT_BOOK_TRG
BEFORE INSERT OR DELETE OR UPDATE OF A_TEXT ON TEXT_BOOK
FOR EACH ROW WHEN (NEW.A_TEXT IS NOT NULL) -- ← 行トリガー(FOR EACH ROW)
DECLARE  -- IS / AS でなく DECLARE
  eSample EXCEPTION;
BEGIN
  IF (INSERTING) THEN
    -- INSERT 時 :OLD は NULL
    :NEW.A_TEXT := 'ABC';
  END IF;
  IF (UPDATING) THEN
    :NEW.A_TEXT := :OLD.A_TEXT || '→' || :NEW.A_TEXT;
    -- UPDATE 時 :OLD :NEW ともセットされる
  END IF;
  IF (INSERTING) THEN
    -- DELETE 時 :NEW は NULL
    NULL;
  END IF;
END;
/

-- 一時的に無効にする
ALTER TABLE table_name DISABLE ALL TRIGGER;
ALTER TABLE table_name ENABLE ALL TRIGGER;
-- 特定のトリガー
ALTER TRIGGER trigger_name DISABLE;
ALTER TRIGGER trigger_name ENABLE;
