
--- PL/SQL スリープ

-- DBMS_LOCK.SLEEP()
GRANT EXECUTE ON DBMS_LOCK TO schema_name;
EXECUTE DBMS_LOCK.SLEEP(10);

-- DBMS_SESSION.SLEEP()
EXECUTE DBMS_SESSION.SLEEP(10);

-- 0.5秒間待機
BEGIN
  FOR i IN 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSTIMESTAMP, 'HH24:MI:SS.ff3'));
    DBMS_SESSION.SLEEP(0.5);
  END LOOP;
END;
